### ISSUE TITLE
how can i add more bar

### ISSUE THREAD

**Issue by b3hr4d** [surikov/RiffShareAndroid#1]
i need make more than 16 bar :
![Capture](https://user-images.githubusercontent.com/35742176/85197591-430fda00-b2f7-11ea-8231-66eb7d140fb1.JPG)

**Comment by surikov** [comment]
Hi. I'm working for new version. It will be compatible with FL Studio. I twill support new XBox and PSP. I've got no time for old projects.
Try to find solution by yourself.
